-- Date Functions in SQL
--SQL DATE FUNCTIONS

--CURRENT DATE
SELECT CURRENT_DATE;

--CURRENT TIME
SELECT CURRENT_TIMESTAMP;

--CURRENT TIME
SELECT CURRENT_TIME;

--CONVERT TIMEZONE
SELECT CONVERT_TIMEZONE('UTC',CURRENT_TIMESTAMP) AS UTC_TIMEZONE;

--CONVERT DATE TO SUBSEQUENT 4 MONTHS AHEAD
SELECT ADD_MONTHS(CURRENT_DATE,4) AS DATE_AFTER_4_MONTHS;

-- 3 MONTHS BACK DATE
SELECT TO_CHAR (ADD_MONTHS(CURRENT_DATE,-3), 'MM-DD-YYYY' ) AS DATE_BEFORE_3_MONTHS;


--GET YR FROM DATE
SELECT DATE_TRUNC('YEAR',CURRENT_DATE) AS YR_FROM_DATE;

SELECT DATE_TRUNC('DAY',CURRENT_DATE) AS DAY_FROM_DATE;

-- GET MTH FROM DATE
SELECT DATE_TRUNC('MONTH',CURRENT_DATE) AS MTH_FROM_DATE;

-- GET DAY FROM DATE
SELECT DATE_TRUNC('DAY',CURRENT_DATE) AS DAY_FROM_DATE;


-- GET LAST DAY OF current MONTH
select last_day(current_date) as last_day_curr_month;


SELECT EXTRACT(DAY FROM CURRENT_DATE) AS DAY;


SELECT EXTRACT (MONTH FROM CURRENT_DATE) AS MONTH;

SELECT TO_CHAR(TO_DATE('1993-08-17'),'YYYY-DD') AS DATE;


SELECT TO_CHAR(TO_DATE('1993-08-17'),'DD-MON') AS DATE;

SELECT ADD_MONTHS(CURRENT_DATE,5) AS DATE_5_MNTHS_AHEAD;


SELECT ADD_MONTHS(CURRENT_DATE,-3) AS DATE_3_MNTHS_BACK;


select datediff('MONTH', '2022-06-01',CURRENT_DATE);

select datediff('DAYS', '2014-06-01',CURRENT_DATE);

select dateadd('month',-2,'2022-06-01');


-- GET LAST DAY OF PREVIOUS MONTH
SELECT LAST_DAY(CURRENT_DATE - INTERVAL '1 MONTH') AS LAST_DAY_PREV_MNTH;

SELECT LAST_DAY(CURRENT_DATE - INTERVAL '2 MONTH') + INTERVAL '1 DAY' AS FIRST_DAY;

SELECT QUARTER(CURRENT_DATE) AS QTR;



SELECT EXTRACT(YEAR FROM CURRENT_DATE) AS YR;
SELECT EXTRACT(MONTH FROM CURRENT_DATE) AS MTH;

-- GET YR FROM DATE
SELECT DATE_TRUNC('YEAR',CURRENT_DATE) AS YR_FROM_DATE;



-- GET MTH FROM DATE
SELECT DATE_TRUNC('MONTH',CURRENT_DATE) AS MTH_FROM_DATE;

-- GET DAY FROM DATE
SELECT DATE_TRUNC('DAY',CURRENT_DATE) AS DAY_FROM_DATE;


select QUARTER(to_date('2024-10-24'));

SELECT to_date('29-11-2024','DD-MM-YYYY') AS DATE_FORMAT;

SELECT TO_CHAR('08-23-2022') AS DATE_CHAR;

SELECT DAYNAME ('1993-08-23');

SELECT TO_CHAR(TO_DATE('1993-08-17'),'DD-MM') AS DATE;



select datediff('day', '2022-06-01',CURRENT_DATE) DATE_DIFFERENCE;


SELECT DATE_TRUNC('DAY',CURRENT_DATE) AS DAY_FROM_DATE;

